NOUN ADP ADJ X PROPN VERB X VERB VERB ADP VERB ADP PROPN NOUN NOUN PROPN NOUN ADJ X NOUN ADP NOUN ADP PROPN X NOUN ADJ X ADJ
PROPN X ADP VERB NUM NOUN ADP PROPN X PROPN PROPN VERB VERB NOUN VERB NOUN NOUN X ADJ
ADJ ADP PROPN VERB NUM NOUN VERB NOUN X VERB NOUN ADP PROPN VERB PROPN ADP NOUN ADV VERB ADV NUM NOUN ADJ NOUN VERB ADP NOUN X NOUN ADP PROPN X PROPN NOUN ADV VERB ADP NOUN NUM X ADJ
ADP PRON X PROPN PROPN VERB ADP NUM NOUN ADP NOUN NOUN ADP NOUN X VERB ADP PROPN X NUM NOUN NOUN ADP PROPN NOUN ADP PROPN NOUN X NOUN CCONJ PROPN ADV VERB X ADJ
PROPN PROPN VERB NUM NOUN ADP VERB ADP PROPN NOUN VERB NOUN X NOUN ADP NOUN VERB VERB ADP NOUN ADV VERB ADP NOUN NUM NOUN PROPN PROPN ADV NUM NOUN X NOUN
PROPN ADV VERB NOUN PRON ADP NOUN NOUN ADP ADJ X NOUN VERB CCONJ ADJ NOUN NOUN X ADJ
PROPN NOUN VERB ADP NOUN NOUN X PROPN PROPN VERB VERB ADP VERB VERB ADP NOUN PROPN X VERB NUM NOUN NOUN VERB DET NOUN VERB PROPN X DET NOUN NOUN ADP PROPN NOUN CCONJ NOUN ADV ADJ ADP VERB VERB NOUN VERB X NOUN NUM NOUN ADJ
PROPN PROPN VERB ADP VERB PROPN VERB PROPN ADP NOUN NUM X ADP NOUN NOUN PROPN NUM VERB VERB NOUN X VERB VERB VERB ADP NOUN NUM X NOUN
NUM NUM X NOUN ADP PROPN PROPN VERB VERB ADP NOUN X VERB NUM NOUN ADJ
PROPN ADP PROPN NOUN ADJ ADP NOUN X
